pycallable:    GTS_encode.GTS_encode_wrapper.Wrapper
title: Encoding of Available Quality Controlled Mangopare Observations into GTS BUFR
description:  >
    This wrapper identifies the quality controlled mangopare observations that 
    are available for encodign. These files are encoded to adhere with
    restrictions and standards of publication on GTS using the ship template. This action is a linked task from
    transfer.qc.mangopare and it is the parent task of transfer.mangopare_to_GTS

out_dir: '/data/obs/mangopare/GTS/'
template: 'GTS_encode_ship'
centre_code: 69
schedule:
    docker:
      image: metocean/ops-qc:bufrtools_v1.0.0
      volumes:
        - /data_exchange:/data_exchange
        - /data:/data
        - /archive/obs/mangopare:/archive/obs/mangopare
    priority:          3
    hourly_cycles:     [0]
#    countdown:         25h
    soft_time_limit:   60min
    memleak_threshold: 5000
    max_retries:       0     # Maximum number of retries before giving up
    retry_delay:       60min  # time to wait for next retry [s]
    link: 
      - transfer.mangopare_to_GTS