name: unittests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unittests
    steps:
      - uses: actions/checkout@v2
      - name: Install System dependencies
        run: sudo apt update && sudo apt install -y $(echo $(cat requirements/ubuntu.txt))
      - name: Docker login
        run: docker login -u mslops -p ${{ secrets.DOCKERHUB_MSLOPS_PASS  }}
      - name: Build Docker Image
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          DATABASE_HOST: '136.156.180.50'
        run: docker build --build-arg GIT_TOKEN -t metocean/moana-bufrtools:encode-${GITHUB_REF#refs/*/} .
      - name: Run tests
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: docker run --rm pytest /source/moana-bufrtools --cov metocean/moana-bufrtools:encode-${GITHUB_REF#refs/*/} 
      - name: Docker push
        run: docker push metocean/moana-bufrtools:encode-${GITHUB_REF#refs/*/}
      - name: Docker logout
        run: docker logout
